spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springclouf-eureka-client
eureka:
  client:
    service-url: 
      defaulzone: http://eureka-dev.com:7001/eureka
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springclouf-eureka-client
eureka:
  client:
    service-url: 
      defaulzone: http://eureka-test.com:7001/eureka
